import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center gap-72 items-center p-5  z-30 absolute w-full text-white mt-1">
          <div>
            <Link href={"/"}>
           <Image src={"/logo .png"} alt="logo"  width={140} height={20}/>
          </Link>
          </div>
          
          <div className="flex gap-8 font-oxanium">
            <Link href="/" className="nav ">
              Home
            </Link>
            <Link href="/about" className="nav">
              About
            </Link>
            <Link href="/skills" className="nav">
              Skills
            </Link>
            <Link href="/contact" className="nav">
              Contact
            </Link>
            <Link href="/projects" className="nav">
              Projects
            </Link>
          </div>
          <div>
             <button className=" bg-[#1D89BD] text-white py-2 px-4 w-[163px] h-[40px] rounded-lg font-poppins">
              Download CV
            </button>
          </div>
        
        
        </div>
        {children}
      </body>
    </html>
  );
}
